### ISSUE TITLE
report session count

### ISSUE THREAD

**Issue by alekm** [djcas9/legacy-snorby#3]
Report is only counting 1 session for every alert.  Many of the alerts i've had have multiple sessions and multiple src/dest.

POLICY GoToMyPC local service running 

Report:
POLICY GoToMyPC local service running 1 10.43.137.48 216.115.208.199 1 (1 session)

Search for event:
Successfully submitted search and found 6 results.

**Comment by djcas9** [comment]
Did that event (all 6) have the same source and destination address?

**Comment by alekm** [comment]
no.  there are multiple sources and destinations.

**Comment by djcas9** [comment]
This can be a hard area to troubleshoot due to the sensitivity of the data. I would need to see the six event in question and the copy of the pdf. Would this be an issue? Please message me the info if possible. not here but using githubs private messaging system. I would also like to thank you for submitting bugs, it really does help me improve and get 1.0.0 done faster.
