### ISSUE TITLE
Dashboard not working and problem with SensorCacheJob

### ISSUE THREAD

**Issue by matherej** [djcas9/legacy-snorby#48]
Hi,

I´ve just installed Snorby2.2.5 and I have a problem. Dashboard always show no events, but when I click to Events tab, events are there. I tried everything what I found here, but it still dont work. And next problem is that SensorCacheJob automatically shut down after 30 minutes and I have to start it again and again manually. 
Please help.
Thanks.

Martin

**Comment by dcarrith** [comment]
Hi matherej,
Have you tried clearing and then running the sensor cache jobs from the rails console in verbose mode?

# cd /path/to/snorby <br />
# sudo rails c <br />
> Snorby::Jobs.clear_cache(true) <br />
> Snorby::Jobs::SensorCacheJob.new(true).perform <br />
> Snorby::Jobs::DailyCacheJob.new(true).perform <br />

I spent a lot of hours trying to track down why the dashboard was not updating.  I posted a couple responses to https://github.com/Snorby/snorby/issues#issue/54 with more details.  But, first step is to run the jobs in verbose mode so you can see if and where it's dying.

**Comment by matherej** [comment]
Hi, so I tried this and there is problem. How to solve it???

irb(main):014:0> Snorby::Jobs::SensorCacheJob.new(true).perform
Sensor 1: Looking for events...
Sensor 1: Found events - processing...
Sensor 1: Found last cache...
Sensor 1: Building cache attributes
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
Sensor 1: - fetching dst ip metrics
Sensor 1: - fetching signature metrics
Sensor 1: Found events - processing...
Sensor 1: Found last cache...
Sensor 1: Building cache attributes
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
undefined method `ip_src' for nil:NilClass
=> nil

Thanks

**Comment by wmjosiah** [comment]
I'm having the same problem, but it's not clear to me why the issue was closed above - did you solve it? I'm getting:
Loading development environment (Rails 3.0.5)
irb(main):001:0> Snorby::Jobs::SensorCacheJob.new(true).perform;
irb(main):002:0\* Snorby::Jobs::SensorCacheJob.new(false).perform;
irb(main):003:0\* Snorby::Jobs::SensorCacheJob.new(true).perform
Sensor 1: Looking for events...
Sensor 1: Found events - processing...
Sensor 1: Found last cache...
Sensor 1: Building cache attributes
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
undefined method `ip_src' for nil:NilClass
undefined method`ip_src' for nil:NilClass
Sensor 1: Looking for events...
Sensor 1: Found events - processing...
Sensor 1: Found last cache...
Sensor 1: Building cache attributes
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
undefined method `ip_src' for nil:NilClass
=> nil
irb(main):004:0>

**Comment by ermalm** [comment]
Same problem here sadly :( 
Can't seem to find a solution either.

Any idea?

**Comment by wmjosiah** [comment]
I have not yet solved this problem. I am running snorby without the dashboard.

**Comment by wmetcalf** [comment]
irb(main):001:0> Snorby::Jobs::SensorCacheJob.new(true).perform
Sensor 1: Looking for events...
Sensor 1: Found last cache...

New Day: 2011-09-13T12:00:00-05:00 - 2011-09-13T12:30:00-05:00
Sensor 1: 51825 events found. Processing.

Processing Batch 1 of 6...
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
Sensor 1: - fetching dst ip metrics
Sensor 1: - fetching signature metrics

Processing Batch 2 of 6...
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
Sensor 1: - fetching dst ip metrics
Sensor 1: - fetching signature metrics

Processing Batch 3 of 6...
Sensor 1: - fetching sensor metrics
Sensor 1: - building proto counts
Sensor 1: - fetch_event_count
Sensor 1: - fetching tcp count
Sensor 1: - fetching udp count
Sensor 1: - fetching icmp count
Sensor 1: - fetching severity metrics
Sensor 1: - fetching src ip metrics
undefined method `ip_src' for nil:NilClass
=> nil
